openapi: 3.0.1
info:
  title: ReportParseAPI
  description: API Definition of ReportParseAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/invoice
paths:
  /details:
    get:
      responses:
        default:
          description: Default response
