openapi: 3.0.1
info:
  title: toolsbpmAPI
  description: API Definition of toolsbpmAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/tools/bpm
- url: https://localhost:8253/tools/bpm
paths:
  /proceso/instancia:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    delete:
      responses:
        default:
          description: Default response
  /roles/{session}:
    get:
      parameters:
      - name: session
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /groups/{session}:
    get:
      parameters:
      - name: session
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /memberships:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /users:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /users/{usr}/session/{session}:
    get:
      parameters:
      - name: usr
        in: path
        required: true
        schema:
          type: string
      - name: session
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /memberships/xUserid/{usrid}/session/{session}:
    get:
      parameters:
      - name: usrid
        in: path
        required: true
        schema:
          type: string
      - name: session
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /membership:
    delete:
      responses:
        default:
          description: Default response
  /group:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /profileMember:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /role:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
