-- =============================================================================
-- 002 - Conocimiento compartido (base de conocimiento minero)
-- =============================================================================
-- Idempotente. Rollback: 002-conocimiento-compartido.rollback.sql
--
-- Este es el activo central del producto: el saber minero curado, comun a
-- todos los clientes. Por ADR-A4 es de SOLO LECTURA para el flujo de consulta;
-- unicamente el circuito de curaduria escribe aca.
--
-- La dimension de embedding es 1024 (cohere/embed-multilingual-v3.0 via
-- OpenRouter). Cambiar de modelo con otra dimension obliga a re-ingestar todo.
-- Ver "Decisiones de diseno" en db/agente/README.md.
-- =============================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- fuente: de donde salio cada pedazo de conocimiento
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.fuente (
    fuente_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo         text        NOT NULL,
    nombre       text        NOT NULL,
    uri          text,
    metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    fec_alta     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fuente_tipo_ck
        CHECK (tipo IN ('documento', 'experto', 'operativo', 'normativa', 'manual')),
    CONSTRAINT fuente_nombre_uk UNIQUE (tipo, nombre)
);

COMMENT ON TABLE  agente.fuente        IS 'Origen de cada chunk de conocimiento compartido: un documento ingestado, un experto entrevistado, o un patron operativo promovido.';
COMMENT ON COLUMN agente.fuente.tipo   IS 'documento | experto | operativo | normativa | manual';
COMMENT ON COLUMN agente.fuente.uri    IS 'Ruta o URL del original, cuando existe. Permite rastrear una afirmacion hasta su fuente.';

-- ---------------------------------------------------------------------------
-- chunk: el conocimiento compartido, vectorizado
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.chunk (
    chunk_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuente_id    bigint      NOT NULL REFERENCES agente.fuente(fuente_id) ON DELETE CASCADE,
    contenido    text        NOT NULL,
    embedding    vector(1024),
    tipo_equipo  text,
    situacion    text,
    confianza    numeric(3,2) NOT NULL DEFAULT 0.50,
    metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    vigente      boolean     NOT NULL DEFAULT true,
    fec_alta     timestamptz NOT NULL DEFAULT now(),
    fec_mod      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT chunk_contenido_ck CHECK (length(btrim(contenido)) > 0),
    CONSTRAINT chunk_confianza_ck CHECK (confianza >= 0 AND confianza <= 1)
);

COMMENT ON TABLE  agente.chunk             IS 'Conocimiento minero compartido entre clientes. SOLO LECTURA para el flujo de consulta (ADR-A4): escribe unicamente el circuito de curaduria.';
COMMENT ON COLUMN agente.chunk.contenido   IS 'El fragmento de texto que se recupera y se le pasa al modelo como contexto.';
COMMENT ON COLUMN agente.chunk.embedding   IS 'vector(1024) - cohere/embed-multilingual-v3.0 via OpenRouter. Cambiar de modelo con otra dimension obliga a re-ingestar.';
COMMENT ON COLUMN agente.chunk.tipo_equipo IS 'Familia de equipo a la que aplica (chancadora, molino, bomba, cinta...). NULL = aplica a cualquiera.';
COMMENT ON COLUMN agente.chunk.situacion   IS 'Situacion operativa que cubre (mantenimiento preventivo, falla, puesta en marcha, seguridad...).';
COMMENT ON COLUMN agente.chunk.confianza   IS 'Entre 0 y 1. Cuanto se puede confiar en esta afirmacion: normativa citada = alta, dicho de un solo experto sin validacion cruzada = baja.';
COMMENT ON COLUMN agente.chunk.vigente     IS 'false = retirado por curaduria. No se borra, para poder auditar que sabia el agente en un momento dado.';

-- Indice vectorial. HNSW da mejor recall/latencia que ivfflat y no necesita
-- reindexar cuando crece la tabla. Distancia coseno, que es la que usan los
-- modelos de embedding de texto.
CREATE INDEX IF NOT EXISTS chunk_embedding_hnsw_ix
    ON agente.chunk USING hnsw (embedding vector_cosine_ops);

-- Los filtros de metadatos se aplican junto con la busqueda vectorial
-- ("dame lo que sepas de chancadoras sobre fallas"), asi que van indexados.
CREATE INDEX IF NOT EXISTS chunk_tipo_equipo_ix ON agente.chunk (tipo_equipo) WHERE vigente;
CREATE INDEX IF NOT EXISTS chunk_situacion_ix   ON agente.chunk (situacion)   WHERE vigente;
CREATE INDEX IF NOT EXISTS chunk_fuente_ix      ON agente.chunk (fuente_id);
CREATE INDEX IF NOT EXISTS chunk_metadata_gin   ON agente.chunk USING gin (metadata);

-- fec_mod se mantiene sola, para no depender de que la aplicacion se acuerde.
CREATE OR REPLACE FUNCTION agente.tg_set_fec_mod()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fec_mod := now();
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS chunk_set_fec_mod ON agente.chunk;
CREATE TRIGGER chunk_set_fec_mod
    BEFORE UPDATE ON agente.chunk
    FOR EACH ROW EXECUTE FUNCTION agente.tg_set_fec_mod();

-- ---------------------------------------------------------------------------
-- Permisos: ACA ESTA LA BARRERA DE ADR-A4
--
-- agente_app solo puede leer. Si el orquestador intentara escribir en el
-- conocimiento compartido por un bug, la base lo rechaza. No es una convencion
-- de codigo: es un permiso del motor.
-- ---------------------------------------------------------------------------
GRANT SELECT ON agente.fuente, agente.chunk TO agente_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON agente.fuente, agente.chunk TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('002-conocimiento-compartido', 'Tablas fuente y chunk, indice HNSW, permisos de solo lectura para agente_app (ADR-A4)')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
