-- =============================================================================
-- 003 - Memoria por cliente, particionada por empr_id
-- =============================================================================
-- Idempotente. Rollback: 003-memoria-cliente.rollback.sql
--
-- Lo que el agente aprende de CADA cliente. Es privado de esa empresa y no se
-- mezcla nunca con el de otra. El aislamiento tiene dos barreras independientes:
--
--   1. Particion declarativa por LIST sobre empr_id (aislamiento fisico).
--   2. Row Level Security sobre la tabla padre (protege del olvido del WHERE).
--
-- La segunda es la que importa de verdad: las fugas entre clientes salen del
-- error humano, no de la ausencia de particiones. Ver tests/test-aislamiento.sql.
-- =============================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- memoria: tabla particionada. No recibe filas directamente; cada empresa
-- escribe en su propia particion, creada con agente.crear_particion_empresa().
--
-- La PK incluye empr_id porque PostgreSQL exige que la clave de particion
-- forme parte de cualquier constraint unica de una tabla particionada.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.memoria (
    empr_id      integer     NOT NULL,
    memoria_id   bigint GENERATED BY DEFAULT AS IDENTITY,
    contenido    text        NOT NULL,
    embedding    vector(1024),
    origen       text        NOT NULL DEFAULT 'consulta',
    entidad_tipo text,
    entidad_id   text,
    metadata     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    fec_alta     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT memoria_pk PRIMARY KEY (empr_id, memoria_id),
    CONSTRAINT memoria_contenido_ck CHECK (length(btrim(contenido)) > 0),
    CONSTRAINT memoria_origen_ck
        CHECK (origen IN ('consulta', 'hallazgo', 'entrevista', 'ingesta', 'manual'))
) PARTITION BY LIST (empr_id);

COMMENT ON TABLE  agente.memoria              IS 'Memoria privada de cada cliente. Particionada por empr_id + RLS. Nunca se comparte entre empresas (ADR-A3/A4).';
COMMENT ON COLUMN agente.memoria.empr_id      IS 'Empresa duena. Sale del JWT que el MCP Gateway ya valido; NUNCA es un parametro que el agente elija.';
COMMENT ON COLUMN agente.memoria.origen       IS 'consulta = surgio de una pregunta del usuario; hallazgo = lo detecto el monitoreo programado; entrevista | ingesta | manual.';
COMMENT ON COLUMN agente.memoria.entidad_tipo IS 'Que entidad del sistema origina la memoria (equipo, ot, deposito...). Permite responder "que sabes de este equipo".';

-- ---------------------------------------------------------------------------
-- Alta de una empresa. Crea su particion y sus indices.
-- Idempotente: si ya existe, no hace nada.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION agente.crear_particion_empresa(p_empr_id integer)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
    v_particion text := format('memoria_e%s', p_empr_id);
BEGIN
    IF p_empr_id IS NULL OR p_empr_id <= 0 THEN
        RAISE EXCEPTION 'empr_id invalido: %', p_empr_id;
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'agente' AND c.relname = v_particion
    ) THEN
        RETURN format('La particion agente.%s ya existia; no se hizo nada.', v_particion);
    END IF;

    EXECUTE format(
        'CREATE TABLE agente.%I PARTITION OF agente.memoria FOR VALUES IN (%s)',
        v_particion, p_empr_id
    );

    -- Un indice HNSW por particion: las busquedas siempre son dentro de una
    -- sola empresa, asi que el indice global no aportaria nada.
    EXECUTE format(
        'CREATE INDEX %I ON agente.%I USING hnsw (embedding vector_cosine_ops)',
        v_particion || '_embedding_hnsw_ix', v_particion
    );
    EXECUTE format(
        'CREATE INDEX %I ON agente.%I (entidad_tipo, entidad_id)',
        v_particion || '_entidad_ix', v_particion
    );

    RETURN format('Particion agente.%s creada.', v_particion);
END
$$;

COMMENT ON FUNCTION agente.crear_particion_empresa(integer) IS
    'Da de alta una empresa en la memoria del agente. Idempotente. Hay que llamarla antes de que esa empresa pueda usar el agente.';

-- ---------------------------------------------------------------------------
-- Row Level Security: la segunda barrera.
--
-- La policy compara empr_id contra el parametro de sesion agente.empr_id, que
-- el orquestador setea con el valor que saco del JWT ya validado:
--
--     SET LOCAL agente.empr_id = '42';
--
-- Si el parametro no esta seteado, la policy no deja ver NADA. Eso es a
-- proposito: fallar cerrado. Una consulta sin contexto de empresa no devuelve
-- filas en vez de devolverlas todas.
-- ---------------------------------------------------------------------------
ALTER TABLE agente.memoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE agente.memoria FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS memoria_aislamiento_empresa ON agente.memoria;
CREATE POLICY memoria_aislamiento_empresa ON agente.memoria
    USING (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer)
    WITH CHECK (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer);

COMMENT ON POLICY memoria_aislamiento_empresa ON agente.memoria IS
    'Un empr_id solo ve y escribe sus propias filas. Sin agente.empr_id seteado no ve nada (falla cerrado). Verificado por tests/test-aislamiento.sql.';

GRANT SELECT, INSERT, UPDATE, DELETE ON agente.memoria TO agente_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON agente.memoria TO agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('003-memoria-cliente', 'Tabla memoria particionada por empr_id, funcion crear_particion_empresa, RLS con fallo cerrado')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
