-- =============================================================================
-- 004 - Cola de conocimiento candidato
-- =============================================================================
-- Idempotente. Rollback: 004-cola-candidatos.rollback.sql
--
-- ADR-A4: el conocimiento compartido solo crece con revision humana. Cuando un
-- patron se repite en varios clientes, el agente lo PROPONE aca; no lo escribe
-- en agente.chunk. La promocion la hace el curador, y queda auditada.
-- =============================================================================

\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS agente.candidato (
    candidato_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenido        text        NOT NULL,
    embedding        vector(1024),
    tipo_equipo      text,
    situacion        text,
    origen           text        NOT NULL,
    evidencia        jsonb       NOT NULL DEFAULT '{}'::jsonb,
    empresas_vistas  integer     NOT NULL DEFAULT 1,
    veces_observado  integer     NOT NULL DEFAULT 1,
    estado           text        NOT NULL DEFAULT 'pendiente',
    curador          text,
    comentario       text,
    chunk_id         bigint      REFERENCES agente.chunk(chunk_id) ON DELETE SET NULL,
    fec_alta         timestamptz NOT NULL DEFAULT now(),
    fec_revision     timestamptz,
    CONSTRAINT candidato_contenido_ck CHECK (length(btrim(contenido)) > 0),
    CONSTRAINT candidato_origen_ck
        CHECK (origen IN ('patron_operativo', 'entrevista', 'documento', 'feedback')),
    CONSTRAINT candidato_estado_ck
        CHECK (estado IN ('pendiente', 'aprobado', 'rechazado', 'duplicado')),
    -- Un candidato revisado tiene que decir quien lo reviso y cuando.
    CONSTRAINT candidato_revision_ck
        CHECK (estado = 'pendiente' OR (curador IS NOT NULL AND fec_revision IS NOT NULL)),
    -- Un candidato aprobado tiene que apuntar al chunk que genero.
    CONSTRAINT candidato_aprobado_ck
        CHECK (estado <> 'aprobado' OR chunk_id IS NOT NULL)
);

COMMENT ON TABLE  agente.candidato                 IS 'Cola de conocimiento propuesto para el compartido. Nada pasa a agente.chunk sin aprobacion humana (ADR-A4).';
COMMENT ON COLUMN agente.candidato.evidencia       IS 'De donde salio: memorias que lo respaldan, consultas que lo originaron, contradicciones detectadas. Es lo que el curador lee para decidir.';
COMMENT ON COLUMN agente.candidato.empresas_vistas IS 'En cuantas empresas distintas se observo el patron. Un patron de una sola empresa no es conocimiento general.';
COMMENT ON COLUMN agente.candidato.chunk_id        IS 'Chunk resultante si se aprobo. Permite rastrear cada pieza del conocimiento compartido hasta su candidatura.';

CREATE INDEX IF NOT EXISTS candidato_pendientes_ix
    ON agente.candidato (fec_alta DESC) WHERE estado = 'pendiente';
CREATE INDEX IF NOT EXISTS candidato_estado_ix ON agente.candidato (estado);
CREATE INDEX IF NOT EXISTS candidato_embedding_hnsw_ix
    ON agente.candidato USING hnsw (embedding vector_cosine_ops);

-- El agente propone; solo el curador decide.
GRANT SELECT, INSERT ON agente.candidato TO agente_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON agente.candidato TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_app, agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('004-cola-candidatos', 'Tabla candidato: cola de curaduria previa al conocimiento compartido (ADR-A4)')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
