-- =============================================================================
-- 005 - Interacciones y feedback
-- =============================================================================
-- Idempotente. Rollback: 005-feedback.rollback.sql
--
-- Cada consulta al agente queda registrada con TODO lo que uso para responder:
-- que fragmentos de conocimiento recupero, que tools MCP llamo, que modelo, y
-- cuanto tardo. Sobre ese registro se cuelga la calificacion del usuario.
--
-- Es el insumo de la proxima iteracion: sin saber que fragmentos y que tools
-- entraron en una respuesta mala, un pulgar abajo no dice nada accionable.
-- =============================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- interaccion: una pregunta y su respuesta
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.interaccion (
    interaccion_id  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    empr_id         integer     NOT NULL,
    usr_id          integer,
    usuario_nick    text,
    canal           text        NOT NULL DEFAULT 'chat_tools',
    pregunta        text        NOT NULL,
    respuesta       text,
    fragmentos_rag  jsonb       NOT NULL DEFAULT '[]'::jsonb,
    tools_llamadas  jsonb       NOT NULL DEFAULT '[]'::jsonb,
    modelo          text,
    tokens_prompt   integer,
    tokens_respuesta integer,
    latencia_ms     integer,
    error           text,
    fec_alta        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT interaccion_pregunta_ck CHECK (length(btrim(pregunta)) > 0),
    CONSTRAINT interaccion_canal_ck
        CHECK (canal IN ('chat_tools', 'entrevista', 'scheduler', 'api'))
);

COMMENT ON TABLE  agente.interaccion                IS 'Registro completo de cada consulta al agente. Base del ciclo de mejora: ver doc/agente/feedback.md.';
COMMENT ON COLUMN agente.interaccion.empr_id        IS 'Sale del JWT ya validado por el gateway. Nunca es un parametro del agente.';
COMMENT ON COLUMN agente.interaccion.fragmentos_rag IS 'Array de {chunk_id | memoria_id, score, origen}. Sin esto, un pulgar abajo no dice donde estuvo el problema.';
COMMENT ON COLUMN agente.interaccion.tools_llamadas IS 'Array de {tool, argumentos, status, latencia_ms}. Permite distinguir "el conocimiento estaba mal" de "la tool MCP fallo".';
COMMENT ON COLUMN agente.interaccion.modelo         IS 'Modelo concreto que respondio, tal como se le pidio a OpenRouter. Es configurable por entorno (ADR-A1), asi que hay que registrar cual fue.';
COMMENT ON COLUMN agente.interaccion.error          IS 'Si la interaccion fallo, que paso. Las interacciones con error tambien se guardan: son las mas informativas.';

CREATE INDEX IF NOT EXISTS interaccion_empresa_fecha_ix ON agente.interaccion (empr_id, fec_alta DESC);
CREATE INDEX IF NOT EXISTS interaccion_modelo_ix        ON agente.interaccion (modelo);
CREATE INDEX IF NOT EXISTS interaccion_con_error_ix     ON agente.interaccion (fec_alta DESC) WHERE error IS NOT NULL;

-- ---------------------------------------------------------------------------
-- feedback: la calificacion del usuario
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.feedback (
    feedback_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interaccion_id uuid        NOT NULL REFERENCES agente.interaccion(interaccion_id) ON DELETE CASCADE,
    util           boolean     NOT NULL,
    comentario     text,
    motivo         text,
    usr_id         integer,
    triaje         text        NOT NULL DEFAULT 'pendiente',
    fec_alta       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT feedback_motivo_ck
        CHECK (motivo IS NULL OR motivo IN
            ('respuesta_incorrecta', 'incompleta', 'no_entendio', 'datos_desactualizados', 'lenta', 'otro')),
    CONSTRAINT feedback_triaje_ck
        CHECK (triaje IN ('pendiente', 'revisado', 'accionado', 'descartado')),
    -- Una persona califica una interaccion una sola vez; puede cambiar de idea
    -- (UPDATE), pero no acumular pulgares.
    CONSTRAINT feedback_una_por_usuario_uk UNIQUE (interaccion_id, usr_id)
);

COMMENT ON TABLE  agente.feedback            IS 'Calificacion del usuario sobre una respuesta. El endpoint de administracion agrupa el feedback negativo por motivo.';
COMMENT ON COLUMN agente.feedback.util       IS 'true = pulgar arriba, false = pulgar abajo.';
COMMENT ON COLUMN agente.feedback.motivo     IS 'Categoria opcional del problema. Es lo que hace agrupable el feedback negativo.';
COMMENT ON COLUMN agente.feedback.triaje     IS 'Estado del feedback en el ciclo de mejora, para no revisar dos veces lo mismo.';

CREATE INDEX IF NOT EXISTS feedback_interaccion_ix ON agente.feedback (interaccion_id);
CREATE INDEX IF NOT EXISTS feedback_negativo_ix
    ON agente.feedback (fec_alta DESC) WHERE util = false AND triaje = 'pendiente';

-- Vista de trabajo del ciclo de mejora: el feedback negativo pendiente, con
-- la pregunta y lo que el agente uso para responderla.
CREATE OR REPLACE VIEW agente.v_feedback_negativo AS
SELECT
    f.feedback_id,
    f.fec_alta,
    f.motivo,
    f.comentario,
    i.interaccion_id,
    i.empr_id,
    i.pregunta,
    i.respuesta,
    i.modelo,
    jsonb_array_length(i.fragmentos_rag) AS cant_fragmentos,
    jsonb_array_length(i.tools_llamadas) AS cant_tools,
    i.error
FROM agente.feedback f
JOIN agente.interaccion i USING (interaccion_id)
WHERE f.util = false
  AND f.triaje = 'pendiente'
ORDER BY f.fec_alta DESC;

COMMENT ON VIEW agente.v_feedback_negativo IS
    'Feedback negativo sin triar, con el contexto de la respuesta. Es lo que consume el endpoint de administracion de E3.';

GRANT SELECT, INSERT, UPDATE ON agente.interaccion, agente.feedback TO agente_app;
GRANT SELECT ON agente.v_feedback_negativo TO agente_app, agente_curador;
GRANT SELECT, INSERT, UPDATE, DELETE ON agente.interaccion, agente.feedback TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_app, agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('005-feedback', 'Tablas interaccion y feedback, vista v_feedback_negativo')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
