-- =============================================================================
-- 006 - Agente entrevistador: agenda, sesiones, hechos y validacion cruzada
-- =============================================================================
-- Idempotente. Rollback: 006-entrevistador.rollback.sql
--
-- El conocimiento tacito de los expertos es el foso defensivo del producto. El
-- modelo de datos sigue el circuito del documento de arquitectura:
--
--   taxonomia + datos MCP + huecos --> agenda priorizada
--   agenda --> sesion (pregunta amplia, repreguntas, estructuracion)
--   sesion --> hechos --> valida el experto --> validacion cruzada --> chunk
--
-- La validacion cruzada queda MODELADA en BD con UI minima en esta version
-- (decision del alcance de E4).
-- =============================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- tema: la agenda priorizada. No es un cuestionario fijo: es una lista de
-- temas con prioridad, que se recalcula con datos reales.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.tema (
    tema_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tema_padre_id   bigint      REFERENCES agente.tema(tema_id) ON DELETE SET NULL,
    nombre          text        NOT NULL,
    descripcion     text,
    tipo_equipo     text,
    situacion       text,
    prioridad       numeric(5,2) NOT NULL DEFAULT 0,
    origen_prioridad jsonb      NOT NULL DEFAULT '{}'::jsonb,
    estado          text        NOT NULL DEFAULT 'pendiente',
    fec_alta        timestamptz NOT NULL DEFAULT now(),
    fec_mod         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT tema_nombre_uk UNIQUE (nombre),
    CONSTRAINT tema_estado_ck
        CHECK (estado IN ('pendiente', 'en_curso', 'cubierto', 'descartado')),
    CONSTRAINT tema_no_es_su_padre_ck CHECK (tema_padre_id IS DISTINCT FROM tema_id)
);

COMMENT ON TABLE  agente.tema                  IS 'Agenda de temas del entrevistador, jerarquica (taxonomia de mantenimiento minero). Se prioriza con datos reales, no a ojo.';
COMMENT ON COLUMN agente.tema.prioridad        IS 'Cuanto mas alta, antes se pregunta. La calcula el orquestador cruzando cuatro fuentes.';
COMMENT ON COLUMN agente.tema.origen_prioridad IS 'Por que tiene esa prioridad: {ots_por_tipo_equipo, consultas_sin_respuesta, rag_debil, peso_taxonomia}. Hace auditable la agenda.';
COMMENT ON COLUMN agente.tema.estado           IS 'cubierto = ya hay conocimiento validado suficiente. Se vuelve a abrir si el uso muestra huecos.';

CREATE INDEX IF NOT EXISTS tema_agenda_ix ON agente.tema (prioridad DESC) WHERE estado = 'pendiente';
CREATE INDEX IF NOT EXISTS tema_padre_ix  ON agente.tema (tema_padre_id);

DROP TRIGGER IF EXISTS tema_set_fec_mod ON agente.tema;
CREATE TRIGGER tema_set_fec_mod
    BEFORE UPDATE ON agente.tema
    FOR EACH ROW EXECUTE FUNCTION agente.tg_set_fec_mod();

-- ---------------------------------------------------------------------------
-- experto: quien aporta conocimiento. Se registra aparte de los usuarios de
-- Dnato porque un experto puede no ser usuario de la plataforma.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.experto (
    experto_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       text        NOT NULL,
    usr_id       integer,
    especialidad text,
    notas        text,
    activo       boolean     NOT NULL DEFAULT true,
    fec_alta     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT experto_nombre_uk UNIQUE (nombre)
);

COMMENT ON TABLE  agente.experto        IS 'Expertos mineros que aportan conocimiento. El acuerdo de que lo capturado es de Trazalog se gestiona fuera del sistema.';
COMMENT ON COLUMN agente.experto.usr_id IS 'Usuario de Dnato, si el experto ademas usa la plataforma. Puede ser NULL.';

-- ---------------------------------------------------------------------------
-- sesion_entrevista: una conversacion con un experto sobre un tema
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.sesion_entrevista (
    sesion_id    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    experto_id   bigint      NOT NULL REFERENCES agente.experto(experto_id) ON DELETE RESTRICT,
    tema_id      bigint      REFERENCES agente.tema(tema_id) ON DELETE SET NULL,
    estado       text        NOT NULL DEFAULT 'abierta',
    transcripcion jsonb      NOT NULL DEFAULT '[]'::jsonb,
    modelo       text,
    fec_inicio   timestamptz NOT NULL DEFAULT now(),
    fec_cierre   timestamptz,
    CONSTRAINT sesion_estado_ck
        CHECK (estado IN ('abierta', 'estructurando', 'en_validacion', 'cerrada', 'abandonada')),
    CONSTRAINT sesion_cierre_ck
        CHECK (estado NOT IN ('cerrada', 'abandonada') OR fec_cierre IS NOT NULL)
);

COMMENT ON TABLE  agente.sesion_entrevista               IS 'Una sesion de entrevista asistida: pregunta amplia, repreguntas, estructuracion en hechos, validacion del experto.';
COMMENT ON COLUMN agente.sesion_entrevista.transcripcion IS 'Array de {rol, texto, ts}. Se guarda completa: la estructuracion en hechos pierde matices que despues sirven.';

CREATE INDEX IF NOT EXISTS sesion_experto_ix ON agente.sesion_entrevista (experto_id, fec_inicio DESC);
CREATE INDEX IF NOT EXISTS sesion_tema_ix    ON agente.sesion_entrevista (tema_id);
CREATE INDEX IF NOT EXISTS sesion_abiertas_ix ON agente.sesion_entrevista (fec_inicio DESC)
    WHERE estado IN ('abierta', 'estructurando', 'en_validacion');

-- ---------------------------------------------------------------------------
-- hecho: lo capturado, ya estructurado, con su estado de validacion
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.hecho (
    hecho_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_id         uuid        NOT NULL REFERENCES agente.sesion_entrevista(sesion_id) ON DELETE CASCADE,
    contenido         text        NOT NULL,
    embedding         vector(1024),
    tipo_equipo       text,
    situacion         text,
    confianza         numeric(3,2) NOT NULL DEFAULT 0.50,
    estado_validacion text        NOT NULL DEFAULT 'borrador',
    chunk_id          bigint      REFERENCES agente.chunk(chunk_id) ON DELETE SET NULL,
    metadata          jsonb       NOT NULL DEFAULT '{}'::jsonb,
    fec_alta          timestamptz NOT NULL DEFAULT now(),
    fec_validacion    timestamptz,
    CONSTRAINT hecho_contenido_ck CHECK (length(btrim(contenido)) > 0),
    CONSTRAINT hecho_confianza_ck CHECK (confianza >= 0 AND confianza <= 1),
    CONSTRAINT hecho_estado_ck
        CHECK (estado_validacion IN
            ('borrador', 'validado_experto', 'en_validacion_cruzada', 'zona_gris', 'aprobado', 'rechazado')),
    -- Un hecho promovido tiene que apuntar al chunk que genero.
    CONSTRAINT hecho_aprobado_ck
        CHECK (estado_validacion <> 'aprobado' OR chunk_id IS NOT NULL)
);

COMMENT ON TABLE  agente.hecho                   IS 'Conocimiento capturado a un experto, estructurado en afirmaciones verificables. Solo llega a agente.chunk cuando esta aprobado.';
COMMENT ON COLUMN agente.hecho.estado_validacion IS 'borrador -> validado_experto (lo confirmo quien lo dijo) -> en_validacion_cruzada -> aprobado | zona_gris | rechazado. zona_gris = los expertos no coinciden; se guarda igual, marcado.';
COMMENT ON COLUMN agente.hecho.chunk_id          IS 'Chunk resultante. Permite rastrear cada pieza del conocimiento compartido hasta la sesion y el experto que la origino.';

CREATE INDEX IF NOT EXISTS hecho_sesion_ix ON agente.hecho (sesion_id);
CREATE INDEX IF NOT EXISTS hecho_estado_ix ON agente.hecho (estado_validacion);
CREATE INDEX IF NOT EXISTS hecho_pendientes_ix
    ON agente.hecho (fec_alta DESC) WHERE estado_validacion IN ('borrador', 'en_validacion_cruzada');
CREATE INDEX IF NOT EXISTS hecho_embedding_hnsw_ix
    ON agente.hecho USING hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------------
-- validacion_cruzada: el veredicto de OTRO experto sobre un hecho
--
-- Con tres expertos, cada aporte se contrasta con los otros dos: si coinciden
-- es solido; si difieren, el hecho queda marcado como zona gris en vez de
-- descartarse. Un desacuerdo entre expertos es informacion, no ruido.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.validacion_cruzada (
    validacion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hecho_id      bigint      NOT NULL REFERENCES agente.hecho(hecho_id) ON DELETE CASCADE,
    experto_id    bigint      NOT NULL REFERENCES agente.experto(experto_id) ON DELETE RESTRICT,
    veredicto     text        NOT NULL,
    comentario    text,
    fec_alta      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT validacion_veredicto_ck
        CHECK (veredicto IN ('coincide', 'discrepa', 'matiza', 'no_opina')),
    -- Un experto opina una sola vez por hecho.
    CONSTRAINT validacion_una_por_experto_uk UNIQUE (hecho_id, experto_id)
);

COMMENT ON TABLE  agente.validacion_cruzada           IS 'Veredicto de otro experto sobre un hecho. Modelado completo; la UI de esta version es minima (lista para aprobar o comentar).';
COMMENT ON COLUMN agente.validacion_cruzada.veredicto IS 'coincide | discrepa | matiza | no_opina. Si hay discrepancia, el hecho pasa a zona_gris y no se promueve tal cual.';

CREATE INDEX IF NOT EXISTS validacion_hecho_ix   ON agente.validacion_cruzada (hecho_id);
CREATE INDEX IF NOT EXISTS validacion_experto_ix ON agente.validacion_cruzada (experto_id);

-- Un experto no valida sus propios hechos: la validacion cruzada perderia
-- sentido. Se controla con trigger porque el dato del autor esta en la sesion.
CREATE OR REPLACE FUNCTION agente.tg_validacion_no_autovalida()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_autor bigint;
BEGIN
    SELECT s.experto_id INTO v_autor
    FROM agente.hecho h
    JOIN agente.sesion_entrevista s USING (sesion_id)
    WHERE h.hecho_id = NEW.hecho_id;

    IF v_autor = NEW.experto_id THEN
        RAISE EXCEPTION
            'El experto % es el autor del hecho %: la validacion cruzada la hace otro experto.',
            NEW.experto_id, NEW.hecho_id;
    END IF;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS validacion_no_autovalida ON agente.validacion_cruzada;
CREATE TRIGGER validacion_no_autovalida
    BEFORE INSERT OR UPDATE ON agente.validacion_cruzada
    FOR EACH ROW EXECUTE FUNCTION agente.tg_validacion_no_autovalida();

-- Vista para la pantalla de validacion cruzada: hechos de otros esperando opinion.
CREATE OR REPLACE VIEW agente.v_hechos_para_validar AS
SELECT
    h.hecho_id,
    h.contenido,
    h.tipo_equipo,
    h.situacion,
    h.estado_validacion,
    h.fec_alta,
    s.experto_id  AS autor_id,
    e.nombre      AS autor,
    t.nombre      AS tema,
    (SELECT count(*) FROM agente.validacion_cruzada v WHERE v.hecho_id = h.hecho_id) AS validaciones
FROM agente.hecho h
JOIN agente.sesion_entrevista s USING (sesion_id)
JOIN agente.experto e ON e.experto_id = s.experto_id
LEFT JOIN agente.tema t ON t.tema_id = s.tema_id
WHERE h.estado_validacion IN ('validado_experto', 'en_validacion_cruzada')
ORDER BY h.fec_alta;

COMMENT ON VIEW agente.v_hechos_para_validar IS
    'Hechos esperando validacion cruzada, con su autor. La UI filtra los del experto logueado (nadie valida lo propio).';

GRANT SELECT, INSERT, UPDATE ON
    agente.tema, agente.experto, agente.sesion_entrevista, agente.hecho, agente.validacion_cruzada
    TO agente_app;
GRANT SELECT ON agente.v_hechos_para_validar TO agente_app, agente_curador;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    agente.tema, agente.experto, agente.sesion_entrevista, agente.hecho, agente.validacion_cruzada
    TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_app, agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('006-entrevistador', 'Tablas tema, experto, sesion_entrevista, hecho y validacion_cruzada; vista v_hechos_para_validar')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
