-- =============================================================================
-- 007 - Notificaciones: dispositivos, notificaciones y envios
-- =============================================================================
-- Idempotente. Rollback: 007-notificaciones.rollback.sql
--
-- Implementa la Opcion C decidida en E0 (doc/agente/analisis-alertas-assetplanner.md
-- seccion 6): el orquestador SOLO ENCOLA aca; el Streaming Integrator poletea
-- agente.envio por CDC y postea al FirebaseConnectorAPI del MI.
--
-- El diseno corrige a proposito seis defectos del mecanismo de AssetPlanner
-- (seccion 6.3 del analisis). Los mas importantes:
--
--   * notificacion (lo que la persona LEE) y envio (el transporte) van
--     separadas: el token FCM nunca llega al frontend.
--   * un envio POR DISPOSITIVO activo, no "el primer token que aparezca".
--   * estado con cuatro valores en vez de un flag binario, porque el conector
--     Firebase responde 202 aunque el envio falle (hallazgo verificado, R4).
-- =============================================================================

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- dispositivo: tokens FCM por usuario de Tools (identidad Dnato)
--
-- No se reusa assetv2.user_token: ese apunta a sisusers de AssetPlanner, que
-- tiene login propio sin Dnato.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.dispositivo (
    dispositivo_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empr_id        integer     NOT NULL,
    usr_id         integer     NOT NULL,
    token          text        NOT NULL,
    user_agent     text,
    activo         boolean     NOT NULL DEFAULT true,
    fec_alta       timestamptz NOT NULL DEFAULT now(),
    fec_ultimo_uso timestamptz,
    CONSTRAINT dispositivo_token_uk UNIQUE (token)
);

COMMENT ON TABLE  agente.dispositivo        IS 'Tokens FCM registrados por usuario de Tools. Un usuario puede tener varios (PC, celular): se notifica a TODOS los activos.';
COMMENT ON COLUMN agente.dispositivo.token  IS 'Registration token de FCM. Unico global: si aparece asociado a otro usuario, el anterior se desactiva.';
COMMENT ON COLUMN agente.dispositivo.activo IS 'false cuando FCM devuelve que el token no es valido, o cuando el usuario revoca el permiso.';

CREATE INDEX IF NOT EXISTS dispositivo_usuario_ix ON agente.dispositivo (empr_id, usr_id) WHERE activo;

-- ---------------------------------------------------------------------------
-- notificacion: lo que la persona lee en la campanita. Sin token, sin datos
-- de transporte.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.notificacion (
    notificacion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empr_id         integer     NOT NULL,
    usr_id          integer,
    rol_destino     text,
    tipo            text        NOT NULL,
    titulo          text        NOT NULL,
    cuerpo          text        NOT NULL,
    severidad       text        NOT NULL DEFAULT 'info',
    entidad_tipo    text,
    entidad_id      text,
    enlace          text,
    dedupe_key      text,
    vence_en        timestamptz,
    leido           boolean     NOT NULL DEFAULT false,
    fec_alta        timestamptz NOT NULL DEFAULT now(),
    fec_lectura     timestamptz,
    CONSTRAINT notificacion_titulo_ck   CHECK (length(btrim(titulo)) > 0),
    CONSTRAINT notificacion_severidad_ck CHECK (severidad IN ('info', 'aviso', 'critica')),
    CONSTRAINT notificacion_tipo_ck
        CHECK (tipo IN ('mtbf_deterioro', 'ot_critica_atrasada', 'hallazgo', 'sistema')),
    -- Tiene que haber destinatario: una persona concreta o un rol.
    CONSTRAINT notificacion_destinatario_ck
        CHECK (usr_id IS NOT NULL OR rol_destino IS NOT NULL),
    CONSTRAINT notificacion_lectura_ck
        CHECK (leido = false OR fec_lectura IS NOT NULL)
);

COMMENT ON TABLE  agente.notificacion             IS 'Lo que el usuario ve en la campanita. Sin token FCM adentro, a diferencia del data_json de AssetPlanner.';
COMMENT ON COLUMN agente.notificacion.empr_id     IS 'Empresa duena. La consulta de la campanita filtra SIEMPRE por empr_id + usuario.';
COMMENT ON COLUMN agente.notificacion.rol_destino IS 'Destinatario por rol cuando la alerta es de empresa y no de una persona (ej. jefe de mantenimiento). La resolucion rol -> usuarios la hace el orquestador. PENDIENTE de definicion funcional del PM.';
COMMENT ON COLUMN agente.notificacion.dedupe_key  IS 'Clave de deduplicacion, con la ventana temporal adentro (ej. mtbf_deterioro:equipo:1234:2026-W36). Sin esto el monitoreo programado repite el mismo hallazgo en cada corrida.';
COMMENT ON COLUMN agente.notificacion.vence_en    IS 'Hasta cuando la notificacion sigue siendo relevante. Se usa para purgar y para que la UI deje de mostrarla; NO participa del indice de deduplicacion.';

-- Deduplicacion: no puede haber dos notificaciones con la misma clave dentro de
-- una empresa.
--
-- La ventana temporal va DENTRO de la dedupe_key (la arma el orquestador), no
-- en el predicado del indice: PostgreSQL exige que las funciones del predicado
-- sean IMMUTABLE y now() no lo es. Asi que en vez de "unica mientras no venza",
-- la regla es "unica para esa ventana", que ademas es determinista.
--
--   Ejemplo de clave: 'mtbf_deterioro:equipo:1234:2026-W36'
--
-- vence_en no participa del indice: sirve para la purga de notificaciones
-- viejas y para que la UI sepa cuando dejar de mostrarlas.
CREATE UNIQUE INDEX IF NOT EXISTS notificacion_dedupe_uk
    ON agente.notificacion (empr_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS notificacion_pendientes_ix
    ON agente.notificacion (empr_id, usr_id, fec_alta DESC) WHERE leido = false;
CREATE INDEX IF NOT EXISTS notificacion_entidad_ix
    ON agente.notificacion (empr_id, entidad_tipo, entidad_id);

-- RLS, igual que en memoria: la campanita no puede ver notificaciones de otra
-- empresa aunque la consulta se olvide del WHERE.
ALTER TABLE agente.notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE agente.notificacion FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS notificacion_aislamiento_empresa ON agente.notificacion;
CREATE POLICY notificacion_aislamiento_empresa ON agente.notificacion
    USING (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer)
    WITH CHECK (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer);

-- ---------------------------------------------------------------------------
-- envio: una fila POR DISPOSITIVO. Es la tabla que poletea el Streaming
-- Integrator.
--
-- envio_id es la columna de polling del CDC: monotona creciente y sin saltos
-- hacia atras, que es lo que necesita @source(type='cdc', mode='polling') para
-- no perder filas. fec_alta serviria, pero dos filas del mismo instante pueden
-- perderse segun como el CDC compare; el id es mas seguro.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agente.envio (
    envio_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notificacion_id bigint      NOT NULL REFERENCES agente.notificacion(notificacion_id) ON DELETE CASCADE,
    dispositivo_id  bigint      REFERENCES agente.dispositivo(dispositivo_id) ON DELETE SET NULL,
    token           text        NOT NULL,
    payload         jsonb       NOT NULL,
    estado          text        NOT NULL DEFAULT 'pendiente',
    intentos        integer     NOT NULL DEFAULT 0,
    ultimo_error    text,
    fec_alta        timestamptz NOT NULL DEFAULT now(),
    fec_envio       timestamptz,
    CONSTRAINT envio_estado_ck
        CHECK (estado IN ('pendiente', 'enviado', 'fallido', 'descartado')),
    -- Un envio marcado como enviado tiene que tener fecha real de envio. Esto
    -- es lo que evita el agujero del fec_realizado de AssetPlanner, que esta
    -- declarado y nunca se escribe.
    CONSTRAINT envio_fecha_ck
        CHECK (estado <> 'enviado' OR fec_envio IS NOT NULL)
);

COMMENT ON TABLE  agente.envio         IS 'Un envio por dispositivo activo del destinatario. Es la tabla que poletea el Streaming Integrator por CDC.';
COMMENT ON COLUMN agente.envio.envio_id IS 'Columna de polling del CDC. Monotona creciente: el @source(type=cdc, mode=polling) la usa como marca de posicion.';
COMMENT ON COLUMN agente.envio.payload IS 'El JSON exacto que se le manda al FirebaseConnectorAPI, envuelto en xformValues -- formato confirmado con una prueba real contra el MI (E0 seccion 6.6).';
COMMENT ON COLUMN agente.envio.estado  IS 'pendiente | enviado | fallido | descartado. NO es un flag binario a proposito: el conector responde 202 aunque el envio falle (R4), asi que "2xx" no alcanza para marcar enviado.';
COMMENT ON COLUMN agente.envio.intentos IS 'Reintentos hechos. Permite parar de insistir con un token muerto en vez de reintentar para siempre.';

CREATE INDEX IF NOT EXISTS envio_pendientes_ix ON agente.envio (envio_id) WHERE estado = 'pendiente';
CREATE INDEX IF NOT EXISTS envio_notificacion_ix ON agente.envio (notificacion_id);
CREATE INDEX IF NOT EXISTS envio_fallidos_ix ON agente.envio (fec_alta DESC) WHERE estado = 'fallido';

-- ---------------------------------------------------------------------------
-- Expandir una notificacion en sus envios, uno por dispositivo activo.
-- Devuelve cuantos genero: 0 significa que el destinatario no tiene ningun
-- dispositivo registrado -- la notificacion igual queda para la campanita.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION agente.expandir_envios(p_notificacion_id bigint)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    v_notif   agente.notificacion%ROWTYPE;
    v_creados integer := 0;
BEGIN
    SELECT * INTO v_notif FROM agente.notificacion WHERE notificacion_id = p_notificacion_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No existe la notificacion %', p_notificacion_id;
    END IF;

    INSERT INTO agente.envio (notificacion_id, dispositivo_id, token, payload)
    SELECT
        v_notif.notificacion_id,
        d.dispositivo_id,
        d.token,
        jsonb_build_object('xformValues', jsonb_build_object(
            'registrationToken',            d.token,
            'notificationTitle',            v_notif.titulo,
            'webPushNotificationBody',      v_notif.cuerpo,
            'webPushNotificationDirection', 'AUTO'
        ))
    FROM agente.dispositivo d
    WHERE d.activo
      AND d.empr_id = v_notif.empr_id
      AND (v_notif.usr_id IS NULL OR d.usr_id = v_notif.usr_id);

    GET DIAGNOSTICS v_creados = ROW_COUNT;
    RETURN v_creados;
END
$$;

COMMENT ON FUNCTION agente.expandir_envios(bigint) IS
    'Genera un envio por dispositivo activo del destinatario, con el payload en el formato xformValues que espera el FirebaseConnectorAPI. Devuelve cuantos genero.';

GRANT SELECT, INSERT, UPDATE ON agente.dispositivo, agente.notificacion, agente.envio TO agente_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON agente.dispositivo, agente.notificacion, agente.envio TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_app, agente_curador;

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('007-notificaciones', 'Tablas dispositivo, notificacion y envio; funcion expandir_envios; RLS sobre notificacion (Opcion C de E0)')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
