-- =============================================================================
-- 008 - Destinatarios de alertas, configurables por empresa
-- =============================================================================
-- Idempotente. Rollback: 008-destinatarios-alerta.rollback.sql
--
-- Decision del PM (2026-09-02): quien recibe una alerta proactiva de empresa
-- --"el equipo X viene fallando mas de lo normal"-- se CONFIGURA por empresa
-- dentro del agente, en vez de heredarse de la identidad de otro producto.
--
-- Por que asi, y no tomando el rol de otro lado:
--
--   * Dnato, que es la identidad de Tools, solo tiene los roles 'admin' y
--     'user', sin empresa. Le llegaria todo al administrador sin importar si
--     es quien decide sobre mantenimiento.
--   * AssetPlanner (assetv2.sisgroups) SI tiene roles ricos y por empresa
--     --Administrador, Mantenedor, Planificador, Supervisor de Taller--, pero
--     tiene login propio sin Dnato: no hay mapeo usuario de Tools <-> usuario
--     de AssetPlanner, y su esquema esta congelado y va a migrar a
--     traz-tools-man.
--
-- Configurarlo en el agente es explicito, auditable, y no lo ata a la
-- identidad de un producto en migracion. La carga inicial de cada cliente se
-- puede sembrar mirando sus roles de AssetPlanner, pero eso es un dato, no una
-- dependencia.
-- =============================================================================

\set ON_ERROR_STOP on

CREATE TABLE IF NOT EXISTS agente.destinatario_alerta (
    destinatario_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empr_id         integer     NOT NULL,
    tipo_alerta     text        NOT NULL,
    usr_id          integer     NOT NULL,
    etiqueta        text,
    activo          boolean     NOT NULL DEFAULT true,
    fec_alta        timestamptz NOT NULL DEFAULT now(),
    fec_mod         timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT destinatario_tipo_ck
        CHECK (tipo_alerta IN ('*', 'mtbf_deterioro', 'ot_critica_atrasada', 'hallazgo', 'sistema')),
    CONSTRAINT destinatario_uk UNIQUE (empr_id, tipo_alerta, usr_id)
);

COMMENT ON TABLE  agente.destinatario_alerta             IS 'Quien recibe cada tipo de alerta, por empresa. Configuracion propia del agente: no depende de los roles de Dnato ni de AssetPlanner.';
COMMENT ON COLUMN agente.destinatario_alerta.tipo_alerta IS 'Tipo de alerta, o "*" para recibir todas. Los valores coinciden con agente.notificacion.tipo.';
COMMENT ON COLUMN agente.destinatario_alerta.usr_id      IS 'Usuario de Tools (identidad Dnato) que recibe la alerta.';
COMMENT ON COLUMN agente.destinatario_alerta.etiqueta    IS 'Funcion legible del destinatario ("Jefe de mantenimiento", "Planificador"). Solo informativa: sirve para que la pantalla de configuracion se entienda y para auditar por que esa persona recibe eso.';

CREATE INDEX IF NOT EXISTS destinatario_empresa_tipo_ix
    ON agente.destinatario_alerta (empr_id, tipo_alerta) WHERE activo;

DROP TRIGGER IF EXISTS destinatario_set_fec_mod ON agente.destinatario_alerta;
CREATE TRIGGER destinatario_set_fec_mod
    BEFORE UPDATE ON agente.destinatario_alerta
    FOR EACH ROW EXECUTE FUNCTION agente.tg_set_fec_mod();

-- Mismo aislamiento que el resto: una empresa no ve ni configura los
-- destinatarios de otra, y sin contexto de empresa no se ve nada.
ALTER TABLE agente.destinatario_alerta ENABLE ROW LEVEL SECURITY;
ALTER TABLE agente.destinatario_alerta FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS destinatario_aislamiento_empresa ON agente.destinatario_alerta;
CREATE POLICY destinatario_aislamiento_empresa ON agente.destinatario_alerta
    USING (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer)
    WITH CHECK (empr_id = NULLIF(current_setting('agente.empr_id', true), '')::integer);

-- ---------------------------------------------------------------------------
-- A quien hay que avisarle de esto.
--
-- Devuelve los usuarios configurados para ese tipo de alerta MAS los que
-- tienen '*'. Si no hay ninguno configurado devuelve vacio: el hallazgo se
-- registra igual en la memoria del cliente, pero no se notifica a nadie --
-- silencio, no un aviso al azar.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION agente.destinatarios_de(p_empr_id integer, p_tipo_alerta text)
RETURNS TABLE (usr_id integer, etiqueta text)
LANGUAGE sql
STABLE
AS $$
    SELECT DISTINCT d.usr_id, d.etiqueta
    FROM agente.destinatario_alerta d
    WHERE d.activo
      AND d.empr_id = p_empr_id
      AND d.tipo_alerta IN (p_tipo_alerta, '*')
    ORDER BY d.usr_id;
$$;

COMMENT ON FUNCTION agente.destinatarios_de(integer, text) IS
    'Usuarios a notificar para un tipo de alerta en una empresa, incluyendo los configurados con "*". Vacio = nadie configurado: el hallazgo se registra pero no se notifica.';

GRANT SELECT, INSERT, UPDATE, DELETE ON agente.destinatario_alerta TO agente_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON agente.destinatario_alerta TO agente_curador;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA agente TO agente_app, agente_curador;

-- El campo rol_destino de agente.notificacion queda como dato informativo: se
-- llena con la etiqueta del destinatario para poder auditar por que le llego,
-- pero la resolucion la hace esta tabla, no un rol externo.
COMMENT ON COLUMN agente.notificacion.rol_destino IS
    'Etiqueta informativa del destinatario, copiada de agente.destinatario_alerta.etiqueta ("Jefe de mantenimiento"). Sirve para auditar por que le llego; la resolucion real la hace agente.destinatarios_de().';

INSERT INTO agente.schema_version (script, descripcion)
VALUES ('008-destinatarios-alerta', 'Tabla destinatario_alerta configurable por empresa, funcion destinatarios_de, RLS')
ON CONFLICT (script) DO UPDATE SET aplicado_en = now();
