openapi: 3.0.1
info:
  title: TangoConnectorAPI
  description: API Definition of TangoConnectorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/tools/tango
paths:
  /synch/in:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /synch/out:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
